//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyHoiThao
{
    using System;
    using System.Collections.Generic;
    
    public partial class KET_QUA_CA_NHAN
    {
        public KET_QUA_CA_NHAN()
        {
            this.KHOAN_CHI = new HashSet<KHOAN_CHI>();
        }
    
        public string MA_MON { get; set; }
        public string MSSV { get; set; }
        public string GIAI { get; set; }
        public string HUY_CHUONG { get; set; }
    
        public virtual MON_THI MON_THI { get; set; }
        public virtual SINH_VIEN SINH_VIEN { get; set; }
        public virtual ICollection<KHOAN_CHI> KHOAN_CHI { get; set; }
    }
}
