//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyHoiThao
{
    using System;
    using System.Collections.Generic;
    
    public partial class KET_QUA_NHOM
    {
        public string MA_MON { get; set; }
        public string MA_NHOM { get; set; }
        public string GIAI { get; set; }
        public string HUY_CHUONG { get; set; }
        public double KHEN_THUONG_NHOM { get; set; }
    
        public virtual NHOM NHOM { get; set; }
    }
}
