//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyHoiThao
{
    using System;
    using System.Collections.Generic;
    
    public partial class KHOAN_THU
    {
        public string MA_PHIEU_THU { get; set; }
        public string MA_LOP { get; set; }
        public string NGUOI_NOP { get; set; }
        public double SO_TIEN { get; set; }
        public System.DateTime NGAY_THU { get; set; }
        public string DIA_CHI { get; set; }
    
        public virtual LOP LOP { get; set; }
    }
}
