//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyHoiThao
{
    using System;
    using System.Collections.Generic;
    
    public partial class LICH_THI
    {
        public string MA_MON { get; set; }
        public string MSSV { get; set; }
        public long STT { get; set; }
        public System.DateTime NGAY_THI_DAU { get; set; }
        public string GIO_THI_DAU { get; set; }
    
        public virtual MON_THI MON_THI { get; set; }
        public virtual SINH_VIEN SINH_VIEN { get; set; }
    }
}
