//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyHoiThao
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOP
    {
        public LOP()
        {
            this.KHOAN_THU = new HashSet<KHOAN_THU>();
            this.NHOMs = new HashSet<NHOM>();
        }
    
        public string MA_LOP { get; set; }
        public string MA_NGANH { get; set; }
        public string TEN_LOP { get; set; }
        public string KHOA_HOC { get; set; }
    
        public virtual ICollection<KHOAN_THU> KHOAN_THU { get; set; }
        public virtual NGANH NGANH { get; set; }
        public virtual ICollection<NHOM> NHOMs { get; set; }
    }
}
