//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyHoiThao
{
    using System;
    using System.Collections.Generic;
    
    public partial class MON_THI
    {
        public MON_THI()
        {
            this.KET_QUA_CA_NHAN = new HashSet<KET_QUA_CA_NHAN>();
            this.LICH_THI = new HashSet<LICH_THI>();
            this.NHOMs = new HashSet<NHOM>();
            this.TRONG_TAI = new HashSet<TRONG_TAI>();
            this.SINH_VIEN = new HashSet<SINH_VIEN>();
        }
    
        public string MA_MON { get; set; }
        public string TEN_MON { get; set; }
    
        public virtual ICollection<KET_QUA_CA_NHAN> KET_QUA_CA_NHAN { get; set; }
        public virtual ICollection<LICH_THI> LICH_THI { get; set; }
        public virtual ICollection<NHOM> NHOMs { get; set; }
        public virtual ICollection<TRONG_TAI> TRONG_TAI { get; set; }
        public virtual ICollection<SINH_VIEN> SINH_VIEN { get; set; }
    }
}
