//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyHoiThao
{
    using System;
    using System.Collections.Generic;
    
    public partial class NGANH
    {
        public NGANH()
        {
            this.LOPs = new HashSet<LOP>();
        }
    
        public string MA_NGANH { get; set; }
        public string TEN_NGANH { get; set; }
    
        public virtual ICollection<LOP> LOPs { get; set; }
    }
}
