//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyHoiThao
{
    using System;
    using System.Collections.Generic;
    
    public partial class NHOM
    {
        public NHOM()
        {
            this.KET_QUA_NHOM = new HashSet<KET_QUA_NHOM>();
        }
    
        public string MA_NHOM { get; set; }
        public string MA_LOP { get; set; }
        public string MA_MON { get; set; }
        public int SO_LUONG { get; set; }
    
        public virtual ICollection<KET_QUA_NHOM> KET_QUA_NHOM { get; set; }
        public virtual LOP LOP { get; set; }
        public virtual MON_THI MON_THI { get; set; }
    }
}
