//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyHoiThao
{
    using System;
    using System.Collections.Generic;
    
    public partial class SINH_VIEN
    {
        public SINH_VIEN()
        {
            this.KET_QUA_CA_NHAN = new HashSet<KET_QUA_CA_NHAN>();
            this.LICH_THI = new HashSet<LICH_THI>();
            this.MON_THI = new HashSet<MON_THI>();
        }
    
        public string MSSV { get; set; }
        public string MA_LOP { get; set; }
        public string TEN_SV { get; set; }
        public string DIA_CHI { get; set; }
        public string SDT { get; set; }
        public string EMAIL { get; set; }
    
        public virtual ICollection<KET_QUA_CA_NHAN> KET_QUA_CA_NHAN { get; set; }
        public virtual ICollection<LICH_THI> LICH_THI { get; set; }
        public virtual ICollection<MON_THI> MON_THI { get; set; }
    }
}
