//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyHoiThao
{
    using System;
    using System.Collections.Generic;
    
    public partial class THU_CHI
    {
        public string NOI_DUNG { get; set; }
        public string SO_TIEN { get; set; }
        public bool THU_HOAC_CHI { get; set; }
    }
}
